### PR TITLE
added search1api-mcp

### PR DESCRIPTION
**Pull request by fatwang2**
Added a new MCP server `search1api` to support web search, link extraction, and content crawling.

## Server Details
- **Server Name**: `search1api`
- **Capabilities**:
  - Perform web search using Search1API.
  - Extract content from specific URLs.
  - Retrieve related links from a given URL (sitemap functionality).

## Motivation and Context
This server integrates all networking logic into a single tool, enabling web search, link extraction, and crawling seamlessly.

## How Has This Been Tested?
Tested using an LLM client (Claude Desktop) with all tools. No compatibility issues or errors observed.

## Breaking Changes
No breaking changes. Existing configurations remain unaffected.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation update

## Checklist

- [x] I have read the [MCP Protocol Documentation](https://modelcontextprotocol.io)
- [x] My server follows MCP security best practices
- [x] I have updated the server's README accordingly
- [x] I have tested this with an LLM client
- [x] My code follows the repository's style guidelines
- [x] New and existing tests pass locally
- [x] I have added appropriate error handling
- [x] I have documented all environment variables and configuration options

## Additional context
This server streamlines the integration of Search1API functionalities into Claude Desktop, enhancing usability and performance.

### CODE REVIEW

**Comment by jspahrsummers** [comment]
I closed your previous PR out, please read why: https://github.com/modelcontextprotocol/servers/pull/117

Please do not submit this again, or you will be restricted from submitting things to this repository.

**Comment by fatwang2** [comment]
I added it into readme just like what you told me...

**Comment by fatwang2** [comment]
can you tell me what should I do, a little confused now

**Review by jspahrsummers — CHANGES_REQUESTED** [review]
We'd be happy to add this to the list, but can you please move it to the "community servers" section? As far as I can tell, this is not an official integration from search1api.

Sorry for my previous misreading of the PR!

**Comment by fatwang2** [comment]
it is official, I am the creator of search1api

Justin Spahr-Summers ***@***.***>于2024年12月3日 周二22:14写道：

**Review by jspahrsummers — APPROVED** [review]
Got it—I can see your personal pages are linked from the official docs as well. Thanks!

**Comment by fatwang2** [comment]
thanks for your comments

**Pull request merged**
