### PR TITLE
feat: Add zep mcp server implementation

### PR DESCRIPTION
**Pull request by paul-paliychuk**
## Server Details

- Server: Created a new `zep` server. 
- Changes to: -

## Motivation and Context
We want to showcase Zep long term memory capabilities by adding our core functionality: persisting memories and retrieving context relevant to the conversation (intending to add more tooling in the future!). 
The user will be able to use this server to provide long term memory to their interactions with the model. Under the hood we are constantly maintaining a user knowledge graph which designed to be queried on each chat turn to inject the relevant context into the conversation. You can find out more in our [docs](https://help.getzep.com/concepts)
## How Has This Been Tested?

I have tested prompts and tools in `@modelcontextprotocol/inspector` as well as in Claude desktop app.
## Breaking Changes
-

## Types of changes

- [x] New MCP Server
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation update

## Checklist

- [x] I have read the [MCP Protocol Documentation](https://modelcontextprotocol.io)
- [x] My server follows MCP security best practices
- [x] I have updated the server's README accordingly
- [x] I have tested this with an LLM client
- [x] My code follows the repository's style guidelines
- [ ] New and existing tests pass locally
- [x] I have added appropriate error handling
- [x] I have documented all environment variables and configuration options

### CODE REVIEW

**Comment by dsp-ant** [comment]
Just want to acknowledge that we have looked at this. We are currently debating how we best structure the servers repo as the contributions grow and particularly with more involved and complex MCP server such as zep in mind. (See https://github.com/orgs/modelcontextprotocol/discussions/32 as a discussion point). We haven't fully decided on the exact approach. Until we know if we will create a form of index list linking to repositories or accept more servers, we are holding off on merging larger servers.

For now my suggestion is to host this on a github repository of zep or a personal one. We can leave this PR open until we fully decided how we proceed.

I hope that's okay.

**Comment by paul-paliychuk** [comment]
@dsp-ant Got it, makes sense to me. Thanks for the update!

**Comment by jspahrsummers** [comment]
Thank you for suggesting this addition! We've now made [some changes](https://github.com/orgs/modelcontextprotocol/discussions/61) to how we'll manage the servers repo going forward.

**TLDR:** We're restructuring the MCP [servers](https://github.com/modelcontextprotocol/servers) repository to focus on reference implementations only. New server implementations should be developed in separate repositories and can be added as links to our README, rather than submitted as PRs to this repository.

In line with that new approach, I'll close out this PR, but we would love to include a link to this server once it's in its own repo. Please do submit a new PR when it's ready!

**Comment by Jmarks199** [comment]
@paul-paliychuk - do you plan to implement this as a server implementation? This is the only reference I could find for Zep. It would be great if it was added!

**Pull request closed without merging**
