### PR TITLE
feat: add MotherDuck server

### PR DESCRIPTION
**Pull request by tdoehmen**
Adding a MCP server for running analytical SQL queries against MotherDuck and local DuckDB.

## Server Details

- Server: mcp-server-motherduck
- Changes to: -

## Motivation and Context
There is currently no mcp server with OLAP capabilities. This adds support for MotherDuck (DuckDB Cloud Data Warehouse) and local DuckDB.

## How Has This Been Tested?
- Tested with Claude Desktop
  - Connect to MotherDuck
  - Connect to an in-memory DuckDB database
  - Show all databases in MotherDuck and query the first 5 rows of one particular table
  - Load a CSV file from an https path and show me some useful aggregate statistics.
 
## Breaking Changes
None 

## Types of changes

- [x] New MCP Server
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist

- [x] I have read the [MCP Protocol Documentation](https://modelcontextprotocol.io)
- [x] My server follows MCP security best practices
- [x] I have updated the server's README accordingly
- [x] I have tested this with an LLM client
- [x] My code follows the repository's style guidelines
- [x] New and existing tests pass locally 
- [x] I have added appropriate error handling
- [x] I have documented all environment variables and configuration options

### CODE REVIEW

**Comment by jexp** [comment]
Kudos @tdoehmen  :)

**Comment by pierrebrunelle** [comment]
Congrats @tdoehmen, you inspired me for a V2 of https://github.com/modelcontextprotocol/servers/pull/95. The initial prompt is a fantastic setup.

**Comment by jacobweiss2305** [comment]
This is really good. Thank you for this.

**Comment by jspahrsummers** [comment]
Thank you for taking the time to build this! We've now made [some changes](https://github.com/orgs/modelcontextprotocol/discussions/61) to how we'll manage the servers repo going forward.

**TLDR:** We're restructuring the MCP [servers](https://github.com/modelcontextprotocol/servers) repository to focus on reference implementations only. New server implementations should be developed in separate repositories and can be added as links to our README, rather than submitted as PRs to this repository.

In line with that new approach, I'll close out this PR, but we would love to include a link to this server once it's in its own repo. Please do submit a new PR when it's ready!

**Comment by jacobweiss2305** [comment]
@jspahrsummers excellent decision thanks for the guidance

**Pull request closed without merging**
