### PR TITLE
Replace snowflake server with more complete version

### PR DESCRIPTION
**Pull request by isaacwasserman**
## Description
I've replaced the Snowflake server listed due to security concerns with the one listed.

## Motivation and Context
- The Snowflake server listed simply implements a single tool `execute_query`.
  - This can execute arbitrary code (including write operations and administrative operations like `ALTER`).  
  - Sanitization (as is done in the reference SQLite and PostgreSQL servers by recognizing the statement keyword and segregating read and write ops) is especially important when dealing with data services like Snowflake as they are often very large and security critical data warehouses.
- The Snowflake server added implements these missing security features as well as making the LLM's ability to perform write operations opt-in with an `--allow-write` configuration flag. The new server additionally provides a read/write resource similar to the SQLite reference server.

## How Has This Been Tested?
I've verified that all features work in the Claude Desktop client as well as the [LangChain MCP Client](https://github.com/rectalogic/langchain-mcp).

## Breaking Changes
No.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation update

## Checklist

- [x] I have read the [MCP Protocol Documentation](https://modelcontextprotocol.io)
- [x] My changes follows MCP security best practices
- [x] I have updated the server's README accordingly
- [x] I have tested this with an LLM client
- [x] My code follows the repository's style guidelines
- [x] New and existing tests pass locally
- [x] I have added appropriate error handling
- [x] I have documented all environment variables and configuration options

## Additional context
I notice in  https://github.com/modelcontextprotocol/servers/pull/284 a second MySQL server was added for a similar reason to the above. I'd also be happy to add this new listing in addition to the existing Snowflake server, rather than replacing it outright.

### CODE REVIEW

**Review by jspahrsummers — APPROVED** [review]
Makes sense, thank you!

**Comment by jspahrsummers** [comment]
FYI @datawiz168. We'd be happy to re-add your server if we can fix the "arbitrary code execution" problem.

**Review by jspahrsummers — APPROVED** [review]

**Comment by datawiz168** [comment]
I'm the first person who contributed the MCP connection to Snowflake for the community. However, someone has deleted my link and replaced it with theirs. The description "This MCP server enables LLMs to interact with Snowflake databases, allowing for secure and controlled data operations." was copied from what I originally wrote. This behavior is inappropriate. Could you please help me restore my contribution?I am deeply outraged by your actions!

**Comment by datawiz168** [comment]
I have deleted the repository and will no longer contribute a single line of code to the MCP community in the future.

**Comment by datawiz168** [comment]
You have shown a complete lack of respect.If you believe your code is superior, you can document it in the README, allowing others to make their own choices. However, directly deleting someone else's link without even changing the title is inappropriate.

**Comment by datawiz168** [comment]
I express my strong indignation at the actions of the MCP community and isaacwasserman.

**Comment by jspahrsummers** [comment]
@datawiz168 Sorry for the negative experience. As mentioned, there's a valid security concern that's been raised. Although this community servers section is indeed "use at your own risk," we would prefer to act to mitigate risk to users when notified about it.

We'd love to restore the link if the risk can be closed in the server implementation! Please feel free to tag me on a PR for review.

**Comment by datawiz168** [comment]
I’ve solved this issue, but you’ll still come up with excuses to remove it. Get lost!

**Pull request merged**
