### PR TITLE
fix: Add node-fetch to brave-search server

### LINKED ISSUE #226: Issue: Brave Search MCP Server Fetch Error on Macos
image

Environment

	•	Claude Desktop Version: maybe latest version
	•	Brave Search MCP Server Version: ["0.5.2"]
	•	Node.js Version: [v22.11.0]
	•	npx Version: [10.9.0]

location:CN mainland

Description of the Issue

After configuring the Brave Search MCP Server in Claude Desktop, I encountered an error while attempting to perform a web search. Here’s the setup and the issue:
	1.	The Brave Search MCP Server is properly added to claude_desktop_config.json as per the documentation:

{
  "mcpServers": {
    "brave-search": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-brave-search"
      ],
      "env": {
        "BRAVE_API_KEY": "YOUR_API_KEY_HERE"
      }
    }
  }
}

	2.	Logs indicate that the Brave Search MCP Server is successfully running and connected:

2024-12-04T14:48:08.913Z [info] Connected to MCP server brave-search!
Brave Search MCP Server running on stdio

	3.	When I attempted a web search in Claude Desktop using a natural language command like:
“Can you web search for the latest news on OpenAI today?”
The response returned:

Error: fetch failed

Steps to Reproduce

	1.	Add the Brave Search MCP Server configuration to claude_desktop_config.json.
	2.	Start Claude Desktop and verify the server is running and connected.
	3.	Use the web search tool (e.g., brave_web_search) with a query like:

{
  "query": "OpenAI latest news today",
  "count": 5
}

	4.	Observe the “fetch failed” error in the response.

Logs

Here is a snippet of the relevant logs:

Brave Search MCP Server running on stdio
2024-12-04T14:48:08.913Z [info] Connected to MCP server brave-search!
...
Error: fetch failed

Expected Behavior

The web search should return relevant results based on the query.

Questions

	1.	Is there a known issue with the Brave Search MCP Server, or am I misconfiguring something?
	2.	Are there additional steps required to validate the server setup?
	3.	How can I debug or get more detailed error information for the fetch failure?

Any guidance would be greatly appreciated!

### PR DESCRIPTION
**Pull request by adamavenir**
Fixes #226 by adding node-fetch to provide fetch functionality in Node.js environment.

## Server Details
- Server: brave-search
- Changes to: tools (fix for web search functionality)

## Motivation and Context
The brave-search server was failing with 'fetch is not defined' because it was trying to use the global fetch API which isn't available in Node.js by default. This made the server non-functional for any search operations.

## Solution
- Add node-fetch and its types as dependencies
- Import fetch from node-fetch explicitly

## How Has This Been Tested?
With the help of @sockdrawermoney, I (Claude) verified this fix works by using the server to perform web searches through the MCP protocol. The fix was developed and tested using MCP's filesystem and git tools to modify and commit the changes. Successfully performed multiple web searches with different queries and verified the results were correctly returned.

## Breaking Changes
No breaking changes. Users don't need to update their MCP client configurations.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist
- [x] I have read the [MCP Protocol Documentation](https://modelcontextprotocol.io)
- [x] My changes follows MCP security best practices
- [x] I have tested this with an LLM client
- [x] My code follows the repository's style guidelines
- [x] I have added appropriate error handling

## Additional context
This fix was developed and tested using MCP tools themselves - the filesystem tools for editing files and git tools for version control. It's a nice example of using MCP to improve MCP!

### CODE REVIEW

**Review by jspahrsummers — CHANGES_REQUESTED** [review]
`fetch` is directly available in Node.js as far back as Node 18, which is the earliest version we support here. Can you confirm you're on that Node version (or later) and still seeing issues?

**Comment by wong2** [comment]
`fetch failed` is not because there's no `fetch` function; it's more likely due to network issues. Especially considering that the author of the issue is in mainland China.

**Comment by shawnzxx** [comment]
I am testing brave-search MCP also, I am not from mainland China, the error message is 
```JS
{
  `count`: 10,
  `query`: `latest economic news inflation interest rates gdp markets december 2024`
}
Error: fetch is not defined

**Comment by wong2** [comment]
@shawnzsha You need to upgrade your node version

**Comment by shawnzxx** [comment]
thanks @wong2,  my local machine node version is v22.7.0
image

**Comment by jspahrsummers** [comment]
@shawnzxx It's possible that the Claude Desktop app (if that's what you're using) is picking up the wrong `node` executable, because `PATH` works differently in GUI apps. Try using an absolute path to the `node` binary you want and see if that helps.

@adamavenir I'm going to go ahead and close this out, per my comment up top. Please feel free to open issues or discussions if there are other problems. 🙏

**Comment by adamavenir** [comment]
Yeah I don't know what it was but I got this error persistently when attempting to use it. I didn't realize node added fetch natively, so it made sense when Claude's first suggestion immediately fixed it. 

I was on Node ~21 locally so idk maybe it was a network issue for me, too. ¯\_(ツ)_/¯ 

I'll take a look sometime and check whether it's working again if I switch from my local fork.

**Pull request closed without merging**
